version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  memcachedbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7memcached
          build_service: centos7memcached
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos7memcachedrel
          build_service: centos7memcachedrel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8memcached
          build_service: centos8memcached
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos8memcachedrel
          build_service: centos8memcachedrel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7memcachedphp73
          build_file: docker-compose.php73.yml
          build_service: centos7memcachedphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8memcachedphp73
          build_file: docker-compose.php73.yml
          build_service: centos8memcachedphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7memcachedphp74
          build_file: docker-compose.php74.yml
          build_service: centos7memcachedphp74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8memcachedphp74
          build_file: docker-compose.php74.yml
          build_service: centos8memcachedphp74
          bintray_uploader: centos8bintray